# Generated by Django 4.2.5 on 2023-10-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('edad_usuario', models.IntegerField()),
                ('ciudad_usuario', models.CharField(max_length=50)),
                ('comuna_usuario', models.CharField(max_length=50)),
                ('insignias_totales', models.IntegerField()),
                ('insignias_ganadas', models.IntegerField()),
            ],
        ),
    ]
