# Generated by Django 4.2.5 on 2023-10-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datos_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato_api_temperatura', models.IntegerField()),
                ('dato_api_radiacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='recomendaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reco_mañana', models.CharField(max_length=100)),
                ('reco_tarde', models.CharField(max_length=100)),
                ('reco_noche', models.CharField(max_length=100)),
            ],
        ),
    ]
