# Generated by Django 4.2.7 on 2023-12-05 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='datos_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato_api_temperatura', models.IntegerField()),
                ('dato_api_radiacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vasos', models.IntegerField(default=10)),
                ('botellas', models.IntegerField(default=10)),
                ('bloqueador', models.IntegerField(default=10)),
                ('ropa', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='recomendaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True)),
                ('numero', models.IntegerField(null=True)),
                ('palabra_clave', models.TextField(default='vasos')),
                ('completado', models.BooleanField(null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cantidad_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vasos_cont', models.PositiveIntegerField()),
                ('botellas_cont', models.PositiveIntegerField()),
                ('bloqueador_cont', models.PositiveIntegerField()),
                ('ropa_cont', models.PositiveIntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
