# Generated by Django 4.2.7 on 2023-11-15 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroagua',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='registrobloqueador',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='registroropa',
            name='usuario',
        ),
    ]
