# Generated by Django 4.2.7 on 2023-11-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_registroropa_confirmacion_ropa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroropa',
            name='confirmacion_ropa',
            field=models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1),
        ),
    ]
