# Generated by Django 4.2.7 on 2023-11-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_registroropa_confirmacion_ropa'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrobloqueador',
            name='confirmacion_bloqueador',
            field=models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1, null=True),
        ),
    ]
