# Generated by Django 4.2.7 on 2023-11-13 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('perfil_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario')),
            ],
        ),
    ]
