# Generated by Django 4.2.5 on 2023-10-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_agua', models.IntegerField()),
                ('vestuario', models.BooleanField()),
                ('bloqueador', models.BooleanField()),
                ('fecha_registro', models.CharField(max_length=50)),
                ('hora_registro', models.CharField(max_length=50)),
            ],
        ),
    ]
