# Generated by Django 4.2.7 on 2023-11-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='correo',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
